/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutGuideRouteImport } from './routes/workout-guide'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as MemberRouteImport } from './routes/member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DietChartRouteImport } from './routes/diet-chart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MemberWorkoutsRouteImport } from './routes/member.workouts'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberFeesRouteImport } from './routes/member.fees'
import { Route as MemberDietRouteImport } from './routes/member.diet'
import { Route as MemberAttendanceRouteImport } from './routes/member.attendance'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'

const WorkoutGuideRoute = WorkoutGuideRouteImport.update({
  id: '/workout-guide',
  path: '/workout-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DietChartRoute = DietChartRouteImport.update({
  id: '/diet-chart',
  path: '/diet-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MemberWorkoutsRoute = MemberWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberFeesRoute = MemberFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDietRoute = MemberDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAttendanceRoute = MemberAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MemberRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/diet-chart': typeof DietChartRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/schedule': typeof ScheduleRoute
  '/workout-guide': typeof WorkoutGuideRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/diet': typeof MemberDietRoute
  '/member/fees': typeof MemberFeesRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/workouts': typeof MemberWorkoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/diet-chart': typeof DietChartRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/schedule': typeof ScheduleRoute
  '/workout-guide': typeof WorkoutGuideRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/diet': typeof MemberDietRoute
  '/member/fees': typeof MemberFeesRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/workouts': typeof MemberWorkoutsRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/diet-chart': typeof DietChartRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/schedule': typeof ScheduleRoute
  '/workout-guide': typeof WorkoutGuideRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/member/attendance': typeof MemberAttendanceRoute
  '/member/diet': typeof MemberDietRoute
  '/member/fees': typeof MemberFeesRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/workouts': typeof MemberWorkoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/diet-chart'
    | '/login'
    | '/member'
    | '/programs'
    | '/schedule'
    | '/workout-guide'
    | '/admin/alerts'
    | '/admin/members'
    | '/admin/payments'
    | '/member/attendance'
    | '/member/diet'
    | '/member/fees'
    | '/member/profile'
    | '/member/workouts'
    | '/admin/'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/diet-chart'
    | '/login'
    | '/programs'
    | '/schedule'
    | '/workout-guide'
    | '/admin/alerts'
    | '/admin/members'
    | '/admin/payments'
    | '/member/attendance'
    | '/member/diet'
    | '/member/fees'
    | '/member/profile'
    | '/member/workouts'
    | '/admin'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/diet-chart'
    | '/login'
    | '/member'
    | '/programs'
    | '/schedule'
    | '/workout-guide'
    | '/admin/alerts'
    | '/admin/members'
    | '/admin/payments'
    | '/member/attendance'
    | '/member/diet'
    | '/member/fees'
    | '/member/profile'
    | '/member/workouts'
    | '/admin/'
    | '/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DietChartRoute: typeof DietChartRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  ScheduleRoute: typeof ScheduleRoute
  WorkoutGuideRoute: typeof WorkoutGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout-guide': {
      id: '/workout-guide'
      path: '/workout-guide'
      fullPath: '/workout-guide'
      preLoaderRoute: typeof WorkoutGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-chart': {
      id: '/diet-chart'
      path: '/diet-chart'
      fullPath: '/diet-chart'
      preLoaderRoute: typeof DietChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/member/workouts': {
      id: '/member/workouts'
      path: '/workouts'
      fullPath: '/member/workouts'
      preLoaderRoute: typeof MemberWorkoutsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/fees': {
      id: '/member/fees'
      path: '/fees'
      fullPath: '/member/fees'
      preLoaderRoute: typeof MemberFeesRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/diet': {
      id: '/member/diet'
      path: '/diet'
      fullPath: '/member/diet'
      preLoaderRoute: typeof MemberDietRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/attendance': {
      id: '/member/attendance'
      path: '/attendance'
      fullPath: '/member/attendance'
      preLoaderRoute: typeof MemberAttendanceRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberRouteChildren {
  MemberAttendanceRoute: typeof MemberAttendanceRoute
  MemberDietRoute: typeof MemberDietRoute
  MemberFeesRoute: typeof MemberFeesRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberWorkoutsRoute: typeof MemberWorkoutsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAttendanceRoute: MemberAttendanceRoute,
  MemberDietRoute: MemberDietRoute,
  MemberFeesRoute: MemberFeesRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberWorkoutsRoute: MemberWorkoutsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DietChartRoute: DietChartRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  ScheduleRoute: ScheduleRoute,
  WorkoutGuideRoute: WorkoutGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
